### ISSUE TITLE
Настройка

### ISSUE THREAD

**Issue by shvisor** [AnastasiaKrapivina/WebInterfaceTesting#1]
```yml
image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &


build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true  # запускаем тест
```
